// Curated portfolio truth. Git pulse is overlaid from optional portfolio-local.js.
// Do not turn activity into a completion claim: capability and proof are separate.
window.PORTFOLIO_DATA = {
  meta: {
    title: 'Mythic Systems',
    subtitle: 'Portfolio control room for Ascentia and its independent creation tools',
    surveyed: '2026-07-18',
    rule: 'No global completion percentage. Report activity, capability, proof, blockers, and the next decision separately.',
  },
  priorities: [
    {
      level: 'review',
      title: 'Leave C: behind — retirement readiness is on this page',
      body: 'Ratified direction (2026-07-18): the portfolio is wholly D:/Ascentia plus its GitHub repos. The Retirement readiness section below classifies every old C: source as retire-ready (junction-covered, awaiting per-entry approval) or blocked with a named reason (skin-forge 147 cloud-only Saved files, landscry winding gate, worldheart file locker, game .vs indexes, quarantine placeholder families). Retirement stays a per-entry, user-approved, verified pass.',
      owner: 'User decision / Portfolio',
    },
    {
      level: 'critical',
      title: 'Restore one coordination truth',
      body: 'The detailed Ascentia dashboard was last curated on July 5/6 while the game moved materially through network proof, P11 combat work, and a large Aether slice. A second dashboard clone also contains one unmerged Designer Compendium commit.',
      owner: 'Portfolio / AscentiaDashboard',
    },
    {
      level: 'active',
      title: 'Keep the game branch published and its record current',
      body: 'codex/designer-compendium is pushed current (Aether replication proof plus the 2026-07-18 D: doc alignment). Remaining discipline: ignored Unreal Content changes still need explicit handoffs, and the detailed gap-data record remains at 2026-07-05 pending re-curation.',
      owner: 'Ascentia',
    },
    {
      level: 'review',
      title: 'Close the two human-facing world gates',
      body: 'Landscry T4b needs final terrain/water presentation plus the owner complete-world verdict. Worldheart is intentionally in lean R50+ visual exploration until the Program Steward says FREEZE.',
      owner: 'Landscry + Worldheart',
    },
    {
      level: 'blocked',
      title: 'Do the Asset Factory security pass before expansion',
      body: 'Safe IDs, approved-root path handling, file serving, reference reads, payload limits, and traversal smokes are the declared P0 gate. CharacterBase and fitting expansion wait behind it.',
      owner: 'ARPG Asset Factory',
    },
    {
      level: 'active',
      title: 'Keep artifact hygiene visible',
      body: 'Every project generates caches, review bundles, and scratch. The standing law (ops/ARTIFACT_HYGIENE.md) is: declared homes or date-stamped scratch, promote-or-delete at closeout, and the Hygiene panel below reports the measured weight. Nothing is auto-deleted.',
      owner: 'All projects / Portfolio',
    },
  ],
  projects: [
    {
      id: 'ascentia',
      name: 'Ascentia',
      futureName: 'Planned product name: Mythic Core',
      role: 'Main game',
      state: 'active',
      phase: 'P11 combat / Aether vertical slice',
      summary: 'The authoritative UE 5.8 open-world RPG. Recent work moved beyond the old dashboard record into dedicated-server verb proof, packaged-profile proof, layered combat presentation, and a substantial environmental Aether system.',
      focus: 'Aether field gameplay and presentation, Magic Sight, Breath-backed sprinting, ground-hugging tells, and current controller/game-mode work.',
      capability: 'A live multiplayer-aware Unreal codebase with recorded network checklist passes and public-profile packaging proof. The new Aether field core has a committed deterministic automation suite, authoring volumes, HUD/castability surfaces, and world interactions.',
      proof: 'Recent commits are evidence of activity, not a clean current-release claim. The survey did not rebuild the six-file modified C++ working tree, and ignored Content assets require an exact handoff.',
      blockers: [
        'The detailed gap-data record predates most July 6-17 work (re-curation pending).',
        'Ignored Unreal Content changes can disappear from Git-based status reporting — handoffs must record asset state explicitly.',
      ],
      next: 'Re-curate gap-data.js against the current evidence set, then continue the P11/Aether slice (node save-spine, Magic Sight art remainder, residue self-refill decision).',
      authority: 'D:/Ascentia/repos/game',
      evidence: [
        'Git HEAD 413b5573 (2026-07-18), pushed; branch clean after the D: doc-alignment commit',
        'Docs/Evidence/Latest and network/public-profile records',
        'Docs/DesignerSurfaces/AetherMagic_README.md',
      ],
      snapshot: { branch: 'codex/designer-compendium', head: '413b5573', date: '2026-07-18', dirty: 0, ahead: 0, behind: 0 },
    },
    {
      id: 'dashboard',
      name: 'AscentiaDashboard + Designer Compendium',
      role: 'Portfolio coordination',
      state: 'attention',
      phase: 'Portfolio consolidation',
      summary: 'The existing coordination depot is the correct home for the portfolio view. Its detailed game matrix, Designer Compendium, tool bridge map, decisions, proof posture, and claim gates remain useful, but its source status has drifted behind the projects.',
      focus: 'Operate the portfolio control room v2: drift detection against curated records, disk/waste hygiene instrumentation, and migration/junction posture surfaced on the page.',
      capability: 'Dependency-free local/static browser dashboard with detailed Ascentia feature data, designer routes, evidence gates, and tool bridge pages.',
      proof: 'The canonical dashboard working tree was copied with exact hash and Git verification to D:/Ascentia/repos/dashboard. Unique commit 93a1b208 is preserved at D:/Ascentia/archives/dashboard-divergence/claude-clone and in dashboard-divergence-93a1b208.bundle; content reconciliation remains pending.',
      blockers: [
        'Curated status date was 2026-07-05 while major game work continued through 2026-07-17.',
        'Archived unique commit 93a1b208 remains intentionally unmerged.',
        'The original C: sources remain retained because source retirement is not authorized.',
      ],
      next: 'User decisions: merge codex/portfolio-control-room to main (deploy gate) and reconcile or retire archived commit 93a1b208; then re-curate gap-data.js.',
      authority: 'D:/Ascentia/repos/dashboard',
      evidence: [
        'Control room v2 commits b409531/660d15c/ab88cf0 (2026-07-18) on codex/portfolio-control-room',
        'Alternate clone commit 93a1b208 (2026-07-07) preserved in archive + bundle',
        'gap-data.js curated date 2026-07-05 (Ascentia detail lags; portfolio survey 2026-07-18 is current)',
      ],
      snapshot: { branch: 'codex/portfolio-control-room', head: 'ab88cf0', date: '2026-07-18', dirty: 0, ahead: null, behind: null },
    },
    {
      id: 'landscry',
      name: 'Landscry v0.2',
      role: 'Authoritative initial terrain',
      state: 'active',
      phase: 'T4b — first composed world',
      summary: 'The clean-room local-first terrain compiler has crossed from contracts and native terrain proof into a canonical streamed UE 5.8 world package and an exercised packaged build.',
      focus: 'Final terrain/water presentation, native-detail complete-world review, and the remaining T4b checkpoint decisions.',
      capability: 'One World Partition map with 16 partitions, 256 compiled sections, Nanite input topology, 64 far-field HLOD actors, collision, packaging, and a seven-station runtime streaming proof.',
      proof: 'The D: repo passes Git, Rust, TypeScript, UE editor build, retained-package validation, and all ten junction checks. New recovery evidence rebuilt 256 sections and 64 HLODs, but two current inspections repeatably failed winding validation; cook/proof were intentionally not run.',
      blockers: [
        'The reconstructed Content is new recovery evidence, not historical byte recovery, and currently fails winding inspection.',
        'Owner complete-world visual acceptance is absent.',
        'Nanite + far-field HLOD versus discrete LOD seam obligation needs a decision.',
        'Older strict-target promotion matrices remain blocked by GitHub billing/spending-limit execution failure.',
      ],
      next: 'Author and inspect final materials, fly the canonical streamed world, record the owner verdict, resolve the LOD obligation, then run the T4b close audit.',
      authority: 'D:/Ascentia/repos/landscry',
      evidence: [
        'T4B_FIRST_COMPOSED_WORLD_SLICE_04_2026-07-17.md',
        'Git HEAD 0d129822 at survey time',
        'Packaged proof: 7/7 stations, streaming/collision report passed',
      ],
      snapshot: { branch: 'agent/t1b-a-declared-boundary', head: 'c4e3979', date: '2026-07-18', dirty: 0, ahead: 0, behind: 0 },
    },
    {
      id: 'worldheart',
      name: 'Worldheart',
      role: 'World composition + architecture',
      state: 'active',
      phase: 'WH-WO-0020 — thematic dressing asset factory R0',
      summary: 'Worldheart is now actively producing deterministic non-Unreal Master Architect building previews. R49 froze the first bounded synthetic technical witness; R50+ is a deliberately fast visual-development sequence, not a gate-acceptance sequence.',
      focus: 'Strengthen visible Mythic Core architectural identity through exact generated mesh while keeping typed non-AI inputs and lightweight catastrophic-integrity checks.',
      capability: 'Frozen R49 produced a 244-component semantic civic-hall mesh, pack, receipt, and four exact-mesh reviews. Its focused tests, independent replay, and 333/333 full suite passed at the recorded revision.',
      proof: 'The governed D: migration preserved the exact dirty/untracked state, worktrees, output, seven detached snapshots, and append-only evidence. The 13 focused WH-WO-0020 tests, local HTTP smoke, Node syntax, and diff check pass; no full suite or gate promotion was performed and G01 remains RED.',
      blockers: [
        'Human architecture, aesthetic, culture, engineering, and production acceptance are absent.',
        'No Unreal consumption is authorized for the active work order.',
        'G01 remains RED and migration verification supplies no missing human acceptance.',
        'Current visual rounds are intentionally not claim-bearing evidence packs.',
        'Branch intentionally has no upstream during R50+ visual rounds; the dressing_factory working tree and the 2026-07-18 doc edits (MIGRATION supersession note, Portfolio Signal section) await commit by the Worldheart lane.',
      ],
      next: 'Continue WH-WO-0020 only within its focused-test boundary; do not run a full suite, rebuild evidence, resolve gates, or claim Unreal acceptance without a governing work order.',
      authority: 'D:/Ascentia/repos/worldheart',
      evidence: [
        'WH-WO-0020_THEMATIC_DRESSING_ASSET_FACTORY_R0.md',
        'WH-HANDOFF-0020_MASTER_ARCHITECT_BUILDING_R49.md',
        'Ignored review outputs r50, r51, and r52 existed at survey time',
      ],
      snapshot: { branch: 'codex/master-architect-visual-r50', head: 'd115798', date: '2026-07-18', dirty: 20, ahead: null, behind: null },
    },
    {
      id: 'assetfactory',
      name: 'ARPG Asset Factory',
      role: 'Game-ready equipment pipeline',
      state: 'blocked',
      phase: 'P0 — security hardening',
      summary: 'A standalone contact-sheet-to-Meshy-to-Blender equipment pipeline that writes review packages to ImportQueue rather than mutating Unreal Content.',
      focus: 'Safe asset-set IDs, approved-root path helpers, file serving, local reference reads, request limits, and traversal/oversize smokes.',
      capability: 'The MVP includes preview/create/inspect tools, contact-sheet planning and slicing, slot-aware prompts, Meshy adapters, approved Blender processing, QA previews, and a Fitting Room handoff.',
      proof: 'The full working tree is preserved on D:. Its package build, eight no-credit smoke checks, and local HTTP surface pass from D:/Ascentia/repos/asset-factory; paid provider actions were not used. main is pushed current as of 2026-07-18 (P0 roadmap and restart scripts now tracked).',
      blockers: [
        'P0 identifies non-uniform set_id sanitization and broad path-prefix checks.',
        'Contact-sheet reference reads and request bodies need explicit bounds.',
        'CharacterBase, character creator, and fitting QA expansion are gated behind P0.',
      ],
      next: 'Implement P0 as one focused pass with traversal and oversize smokes; only then resume paired-slot, image configuration, base-body, or fitting work.',
      authority: 'D:/Ascentia/repos/asset-factory',
      evidence: [
        'docs/development-priority-roadmap.md',
        'Git HEAD b1821de5; six working-tree paths at survey time',
        'ImportQueue is a human-review boundary, not an Unreal import claim',
      ],
      snapshot: { branch: 'main', head: 'b8b0522', date: '2026-07-18', dirty: 0, ahead: 0, behind: 0 },
    },
    {
      id: 'interfaceforge',
      name: 'Interface Art Forge / Mythic Skin Forge',
      role: 'Game UI skin tooling',
      state: 'attention',
      phase: 'V1 implemented / Marketplace hardening',
      summary: 'Interface Art Forge is the plugin authority; MythicSkinForge is an unversioned UE 5.8 proving-ground project that contains a copied plugin and generated UI assets. They are one product track, not two independent roadmaps.',
      focus: 'Marketplace packaging and clean-install evidence. The canonical-to-vendored sync path now exists: sync-vendored.ps1 + Docs/VENDORED_SYNC.md (docs re-synced 2026-07-18).',
      capability: 'The plugin documents a complete V1 workbench: standalone and embedded UMG flows, Skin Fit templates/masks, Images 2 generation, slicing, candidate lifecycle, style references, presentation controls, and supported UMG write-back.',
      proof: 'The canonical repo passes descriptor/module/preset validation and is pushed current at 6370b66 on claude/docs-accuracy. All seven production files are content-identical across canonical, Game, and Skin copies after newline normalization (raw hashes differ only by CRLF-vs-LF, verified 2026-07-18); the successful UE 5.8 Game build compiled both equivalent modules.',
      blockers: [
        'MythicSkinForge is not under Git and mixes sample content, generated assets, caches, and the copied plugin (it now carries an AGENTS.md stating the canonical relationship).',
        'The workbench remains a large ownership monolith slated for service/adaptor extraction.',
        'Clean UE screenshots, demo video, API-key shipping policy, and broader smoke coverage remain; compat wording updated to UE 5.8.',
        'HISTORY SPLIT (found 2026-07-18): GitHub main was force-replaced with a single release-prep commit b4dcfac (Marketplace/ folder, BuildFabPackage.ps1, ~374-line larger editor module) that shares NO history with the local canonical line. claude/docs-accuracy is pushed but a PR is impossible until the user reconciles which line is truth.',
      ],
      next: 'USER DECISION: reconcile the two InterfaceArtForge histories — remote b4dcfac release-prep versus the local docs-accuracy line (the one actually vendored into the game and skin-forge). Then merge and capture the Marketplace evidence set using sync-vendored.ps1 for installs.',
      authority: 'D:/Ascentia/repos/interface-forge (plugin); D:/Ascentia/sandboxes/skin-forge (proving ground only)',
      evidence: [
        'Feature_Set_Inventory.md V1 completion section',
        'Architecture_Review.md refactor targets',
        'sync-vendored.ps1 -DocsOnly run 2026-07-18: 7 docs refreshed in both vendored copies; production files newline-only diffs',
      ],
      snapshot: { branch: 'claude/docs-accuracy', head: '6370b66', date: '2026-07-18', dirty: 0, ahead: 0, behind: 0 },
    },
    {
      id: 'skinforge',
      name: 'Mythic Skin Forge',
      role: 'Interface Art Forge proving ground',
      state: 'attention',
      phase: 'D: sandbox migration with retained offline exception',
      summary: 'The UE 5.8 proving ground is preserved at D:/Ascentia/sandboxes/skin-forge as a sandbox, not the canonical plugin authority.',
      focus: 'Retain authoritative sample/generated content, keep the canonical Interface Forge relationship explicit, and recover the 147 unavailable Saved files only if OneDrive recall is later authorized.',
      capability: 'All 1,018 locally readable files are SHA-256 verified on D:, including the complete accessible plugin and project surfaces.',
      proof: 'The target intentionally omits exactly 147 unavailable Saved files. The original placeholder-bearing source remains untouched and no compatibility redirect is installed.',
      blockers: ['147 OneDrive placeholder files in Saved were unavailable during migration.'],
      next: 'Operate from D: for available sandbox work and preserve the C: source for possible later placeholder recall.',
      authority: 'D:/Ascentia/sandboxes/skin-forge (proving ground only)',
      evidence: ['D:/Ascentia/ops/verification/skin-forge-tree.json'],
      snapshot: { branch: '', head: '', date: '2026-07-18', dirty: 0, ahead: null, behind: null },
    },
    {
      id: 'themeforge',
      name: 'ThemeForge library family',
      role: 'Read-only Worldheart visual upstream',
      state: 'active',
      phase: 'Verified 45-theme corpus on D:',
      summary: 'ThemeForge, PCG Sheet Library, and PCG Contact Sheets are migrated together under D:/Ascentia/libraries/themeforge with lineage and immutable evidence preserved.',
      focus: 'Consume the migrated reflib read-only, keep mutable incremental state D:-native, and preserve historical manifests without path rewriting.',
      capability: '47,490 files, 22,729 PNGs, the processed reflib/out corpus, gates, state, handoffs, immutable snapshots, and unborn tooling Git state are present on D:.',
      proof: 'Complete SHA-256 family manifests, 45-theme reconciliation checks, current-manifest dry runs, and all 1,819 immutable snapshot PNG checks pass.',
      blockers: [],
      next: 'Use D: defaults for future runs; do not regenerate evidence merely to prove access.',
      authority: 'D:/Ascentia/libraries/themeforge',
      evidence: ['D:/Ascentia/ops/verification/themeforge-family-corpus.json'],
      snapshot: { branch: '', head: '', date: '2026-07-18', dirty: 0, ahead: null, behind: null },
    },
  ],
  flows: [
    {
      from: 'Landscry v0.2',
      contract: 'Pinned terrain snapshot + explicit lineage',
      to: 'Worldheart',
      then: 'Typed world/architecture output → Ascentia (future authorized consumption)',
      posture: 'Defined boundary; no automatic live integration',
    },
    {
      from: 'ARPG Asset Factory',
      contract: 'ImportQueue review package',
      to: 'Human review / Fitting Room',
      then: 'Guarded Unreal intake → Ascentia',
      posture: 'Standalone tool; direct Content writes forbidden',
    },
    {
      from: 'Interface Art Forge',
      contract: 'Versioned plugin install + reviewed candidate art',
      to: 'MythicSkinForge proving ground',
      then: 'Validated skin assets/workflow → Ascentia UI',
      posture: 'Current copied plugin is drifted; sync is not yet repeatable',
    },
    {
      from: 'All projects',
      contract: 'Status + evidence + blocker + next decision',
      to: 'AscentiaDashboard',
      then: 'Human portfolio decisions',
      posture: 'Reporting relationship only; dashboard never overrides project law',
    },
  ],
  authority: [
    {
      name: 'Main game identity',
      canonical: 'D:/Ascentia/repos/game',
      noncanonical: 'The original Ascentia source is retained; Unreal Projects/MythicCore, MythicCore 5.3, GitHub/MythicCore, and Backups - Mythic Core are incomplete quarantined provenance.',
    },
    {
      name: 'Terrain identity',
      canonical: 'D:/Ascentia/repos/landscry',
      noncanonical: 'Landscry is the earlier/reference line; Landscry-codex-torch is a worktree, not a separate product.',
    },
    {
      name: 'Dashboard identity',
      canonical: 'D:/Ascentia/repos/dashboard',
      noncanonical: 'Both original C: dashboard sources are retained; the Claude clone and verified bundle preserve unique commit 93a1b208 as archive provenance.',
    },
    {
      name: 'Worldheart identity',
      canonical: 'D:/Ascentia/repos/worldheart plus its signed work orders/handoffs',
      noncanonical: 'Worldheart_output, candidate/evidence clones, and worktrees are outputs or audit surfaces—not restore authorities.',
    },
    {
      name: 'UI tool identity',
      canonical: 'D:/Ascentia/repos/interface-forge',
      noncanonical: 'D:/Ascentia/sandboxes/skin-forge is the proving ground; its accessible production files are normalized-content-identical while 147 Saved placeholders remain unavailable.',
    },
    {
      name: 'Asset Factory identity',
      canonical: 'D:/Ascentia/repos/asset-factory',
      noncanonical: 'The original OneDrive working tree is retained only for rollback during the compatibility period.',
    },
    {
      name: 'ThemeForge family identity',
      canonical: 'D:/Ascentia/libraries/themeforge',
      noncanonical: 'The three original source roots are retained for rollback; historical path fields remain immutable provenance.',
    },
  ],
};
